### ISSUE TITLE
Support for literal types would be a great addition

### ISSUE THREAD

**Issue by mncoldsmoke** [mivui/vue-prop#1]
It would be great to have a way to use literal types with the ts-prop api.

When using a literal type like:
type Easing = "ease-in" | "ease-out" | "ease-in-out";

it seems that the type has to be passed in as a string, and loses it's type-safety. I have tried using object<Easing> but that gives a Vue error that it is expecting an object but got a string.

**Comment by uinio** [comment]
Update 3.0 Please read README.md

**Comment by mncoldsmoke** [comment]
Thank you, this works great!
